/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VisVoteCounter {
        "counterTitle": string;
    }
}
declare global {
    interface HTMLVisVoteCounterElement extends Components.VisVoteCounter, HTMLStencilElement {
    }
    var HTMLVisVoteCounterElement: {
        prototype: HTMLVisVoteCounterElement;
        new (): HTMLVisVoteCounterElement;
    };
    interface HTMLElementTagNameMap {
        "vis-vote-counter": HTMLVisVoteCounterElement;
    }
}
declare namespace LocalJSX {
    interface VisVoteCounter {
        "counterTitle"?: string;
        "onCountChanged"?: (event: CustomEvent<number>) => void;
    }
    interface IntrinsicElements {
        "vis-vote-counter": VisVoteCounter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vis-vote-counter": LocalJSX.VisVoteCounter & JSXBase.HTMLAttributes<HTMLVisVoteCounterElement>;
        }
    }
}
